@startuml
title Flujo de navegación - SeaBattle App

skinparam componentStyle rectangle
skinparam packageStyle rectangle
skinparam defaultTextAlignment center
skinparam ArrowColor DarkSlateGray
skinparam ComponentBorderColor Black
skinparam BackgroundColor #fdfdfd

package "Entrada" {
    component "Splash Screen\n" as SplashScreen
}

package "Autenticación" {
    component "Welcome\n(Selección método)" as Welcome
    component "Login\n(Inicio de sesión)" as Login
    component "Register\n(Registro)" as Register
}

package "Núcleo" {
    component "Home\n(Pantalla principal)" as Home
    component "Profile\n(Gestión del perfil)" as Profile
    component "BattlePlan\n(Organización del tablero)" as BattlePlan
    component "Play\n(Busqueda de partida)" as Play
    component "Gameboard\n(Partida)" as Gameboard
}

' Flujo principal
SplashScreen --> Welcome : no autenticado
SplashScreen --> Home : autenticado

Welcome <--> Login
Welcome <--> Register

Login --> Home : login exitoso
Register --> Home : registro exitoso

' Navegación interna desde Home
Home <--> Play : buscar partida
Home <--> BattlePlan : cambio de tab
Home <--> Profile : cambio de tab

' Flujo dentro del juego
Play --> Gameboard : partida iniciada
Gameboard --> Home : partida finalizada

@enduml
